---
- name: OS-based overrides
  include_vars: "{{ item }}"
  with_first_found:
    - skip: true
      files:
        - "{{ ansible_facts['os_family'] | lower }}.yaml"

- name: Stat the required files
  ansible.builtin.stat:
    path: "{{ item | expanduser }}"
  register: check_files
  loop:
    - "{{ ssh_pub_file }}"
    - "{{ pull_secrets_file }}"
    - "{{ cluster_password_file }}"
    - "{{ aws_cred_file }}"

- name: Fail if any file does not exist
  ansible.builtin.fail:
    msg: "{{ item }} not found"
  when: not item.stat.exists
  loop: "{{ check_files.results }}"

# Other checks needed go here
