---
- name: Deploy AWS clusters
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - ./vars/defaults.yml
  tasks:
    - name: Create Lab destination folders (if not existing)
      ansible.builtin.file:
        path: "{{ item }}"
        recurse: true
      loop:
        - "{{ workshop_ocp_install_path }}"
        - "{{ workshop_ocp_client_path }}"
        - "{{ workshop_student_files_path }}"

    - name: Check requirements
      ansible.builtin.include_role:
        name: check-requirements

    - name: Make sure the openshift installation base folder is empty
      ansible.builtin.find:
        paths: "{{ workshop_ocp_install_path }}"
        file_type: any
        hidden: true
      register: files_found_in_workspace

    - name: Fail if {{ workshop_ocp_install_path }} folder is not empty
      ansible.builtin.fail:
        msg: |
          Refusing to proceed as there are files in {{ workshop_ocp_install_path }}, which means there
          are leftovers from a previous installation
      when: files_found_in_workspace.matched > 0

    - name: Info about clusters to be deployed
      vars:
        msg: |
          Number of clusters to be installed: {{ clusters_count }}
          AWS Region: {{ aws_region }}

          Control Nodes: {{ "%02d" | format(controlplane_replicas) }} [{{ controlplane_type }}]
          Compute Nodes: {{ "%02d" | format(compute_replicas) }} [{{ compute_type }}]
      ansible.builtin.debug:
        msg: "{{ msg.split('\n') }}"

    - name: Prompt if the above is okay
      ansible.builtin.pause:
        prompt: "Do you want to proceed installing all the clusters (yes/no)?"
      register: check_continue

    - name: Fail if not confirmed continue
      ansible.builtin.fail:
        msg: "Stopping here as we did not confirm"
      when: not (check_continue.user_input | bool)

    - name: Fetch OCP clients
      ansible.builtin.include_role:
        name: fetch-ocp-clients

    - name: Deploy OCP clusters
      ansible.builtin.include_role:
        name: deploy-clusters
